PROJECT_VARIABLE_NAME = 'SETTINGS_COMPOSER_PROJECT'
SITE_VARIABLE_NAME = 'SETTINGS_COMPOSER_SITE'
ENV_VARIABLE_NAME = 'SETTINGS_COMPOSER_ENV'
SWITCHES_VARIABLE_NAME = 'SETTINGS_COMPOSER_SWITCHES'
VERBOSE_VARIABLE_NAME = 'SETTINGS_COMPOSER_VERBOSE'

TRUE_VALUES = ('true', 'yes', 'y', '1')

EXCLUDE_PREFIX = 'SETTINGS_COMPOSER_EXCLUDE_'
UPDATE_PREFIX = 'SETTINGS_COMPOSER_UPDATE_'
